Add support to pass ref into command
Add support to pass ref into command so that it can be scripted more
easily.

This relates to issue #1

ps-id: 6ae37db8-38d5-478c-b1d8-e1d3c443e3c4

diff --git a/git-ticket-summary b/git-ticket-summary
--- a/git-ticket-summary
+++ b/git-ticket-summary
@@ -1,6 +1,19 @@
 #!/bin/sh
 
 TICKET_ID=$1
+REF=$2
+
+if [ -z $TICKET_ID ]; then
+	echo "Error: missing <ticket-id> argument"
+	echo "Usage: git-ticket-summary <ticket-id> <ref>"
+	exit 1
+fi
+
+if [ -z $REF ]; then
+	echo "Error: missing <ref> argument"
+	echo "Usage: git-ticket-summary <ticket-id> <ref>"
+	exit 2
+fi
 
 LOCAL_BRANCH=`git name-rev --name-only HEAD`
 TRACKING_BRANCH=`git config branch.$LOCAL_BRANCH.merge`
@@ -21,10 +34,10 @@ echo "ticket: ${TICKET_ID}"
 echo "repository: ${TRACKING_REMOTE_URL}"
 
 echo "\n## Commits\n"
-git log --pretty=format:"%C(yellow)%h%Creset - %G? -%C(red)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset $COMMIT_BASE_URL%H" --grep=$TICKET_ID
+git log ${REF} --pretty=format:"%C(yellow)%h%Creset - %G? -%C(red)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset $COMMIT_BASE_URL%H" --grep=$TICKET_ID
 
 echo "\n## Files created / deleted / modified\n"
 
-INVOLVED_FILES=`git log --pretty=format:"%H" --grep=$TICKET_ID | xargs -n 1 git diff-tree --no-commit-id --name-only -r `
+INVOLVED_FILES=`git log ${REF} --pretty=format:"%H" --grep=$TICKET_ID | xargs -n 1 git diff-tree --no-commit-id --name-only -r `
 
 echo "$INVOLVED_FILES" | sort | uniq | xargs -n 1 -I % echo ${BASE_URL}/blob/${SHORT_TRACKING_BRANCH}/%
